import type { Metadata } from "next";
import { Inter, Lato, Roboto_Flex } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import LoginModal from "./components/LoginModal";
import SessionProvider from "./lib/provider";

const inter = Inter({ subsets: ["latin"] });
const font = Roboto_Flex({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar></Navbar>
          <div className="container mx-auto">{children}</div>
          <LoginModal></LoginModal>
          <Footer></Footer>
        </SessionProvider>
      </body>
    </html>
  );
}
